language: python
python:
- "3.7"
# setup environment
env:
- DJANGO_VERSION=3.1.3
- DJANGO_SETTINGS_MODULE='foodapi.settings'
# install dependencies
install:
- pip install -r requirements.txt
- pip install coveralls

# before_script:
#   - createdb foodapi
# run test scripts
script:
- ./manage.py makemigrations
- ./manage.py migrate
- pytest  
# save coverage
after_success:
  - "coveralls"
