language: python

python:
    - "3.7"
env:
    - SECRET_KEY='TEST'
services:
   - postgresql
install:
   - pip install -r requirements.txt
   - pip install coveralls
script:
    -  pytest
after_success:
    - codecov
