language: python
python:
- "3.7"
# setup environment
env:
- DJANGO_VERSION=3.1.3
- DJANGO_SETTINGS_MODULE='foodapi.settings'
# install dependencies
install:
- pip install -r requirements.txt
- pip install coveralls

# run test scripts
script:
- pytest
  
# save coverage
after_success:
  - "coveralls"
