language: python

python:
    - "3.7"
env:
    - SECRET_KEY='TEST'
services:
   - postgresql
before_script:
  - psql -c 'create database foodapi;' -U postgres

install:
   - pip install -r requirements.txt
   - pip install coveralls
script:
    -  pytest
after_success:
    - codecov
