# Generated by Django 3.1.3 on 2021-11-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('admin', 'Admin'), ('customer_care', 'Customer Care'), ('food_attendant', 'Food attendant')], null=True),
        ),
    ]
