# Generated by Django 3.1.3 on 2021-11-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211103_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('FOOD_ATTENDANT', 'customer_care'), ('CUSTOMER_CARE', 'customer_care'), ('NORMAL_USER', 'normal_user')], max_length=50, null=True),
        ),
    ]
