# Generated by Django 3.1.3 on 2021-11-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'food_attendant'), (3, 'customer_care'), (4, 'normal_user')], primary_key=True, serialize=False)),
            ],
        ),
    ]
